addWords("A2", `
to follow = seguir
to continue = continuar/seguir
to happen = pasar/ocurrir/suceder
to pass = pasar
to spend (time) = pasar
to spend (money) = gastar
to save (money) = ahorrar
to save (rescue) = salvar
to lose = perder
to win = ganar
to earn = ganar
to receive = recibir
to show = mostrar/enseñar
to teach = enseñar
to explain = explicar
to choose = elegir/escoger
to decide = decidir
to prefer = preferir
to allow = permitir/dejar
to let = dejar
to hold = sostener/tener
to keep = guardar/mantener
to get (obtain) = conseguir/obtener
to become = convertirse/hacerse/volverse
to seem = parecer
to appear = aparecer
to exist = existir
to belong = pertenecer
to fall = caer/caerse
to throw = tirar/lanzar/echar
to catch = coger/atrapar
to push = empujar
to pull = tirar/jalar
to break = romper
to fix = arreglar
to build = construir
to cut = cortar
to draw = dibujar
to paint = pintar
to climb = subir/escalar
to go up = subir
to go down = bajar
to get on = subir
to get off = bajar
to fly = volar
to drive = conducir/manejar
to park = aparcar/estacionar
to cross = cruzar
to turn = girar/doblar
to stop = parar/detener
to move = mover/moverse
to move (house) = mudarse
to stay = quedarse
to sit = sentarse
to stand up = ponerse de pie/levantarse
to lie down = acostarse/tumbarse
to go to bed = acostarse
to dress (oneself) = vestirse
to shower = ducharse
to bathe = bañarse
to brush = cepillar/cepillarse
to shave = afeitarse
to comb = peinarse
to put on (clothes) = ponerse
to take off (clothes) = quitarse
to fit = caber/quedar
to cost = costar
to count = contar
to measure = medir
to weigh = pesar
to fill = llenar
to empty = vaciar
to heat = calentar
to boil = hervir
to fry = freír
to bake = hornear
to taste = probar
to smell = oler
to touch = tocar
to kiss = besar
to hug = abrazar
to smile = sonreír
to laugh = reír/reírse
to cry = llorar
to shout = gritar
to whisper = susurrar
to cough = toser
to breathe = respirar
to die = morir
to be born = nacer
to grow = crecer
to marry = casarse
to get married = casarse
to divorce = divorciarse
to meet (someone) = conocer/encontrarse
to know how to = saber
to agree = estar de acuerdo
to discuss = discutir
to argue = discutir
to complain = quejarse
to apologize = disculparse/pedir perdón
to thank = agradecer
to greet = saludar
to invite = invitar
to celebrate = celebrar/festejar
to enjoy = disfrutar
to have fun = divertirse
to get bored = aburrirse
to worry = preocuparse
to be afraid = tener miedo
to be right = tener razón
to be lucky = tener suerte
to be sleepy = tener sueño
to be in a hurry = tener prisa
to hurry = darse prisa/apurarse
to bother = molestar
to hurt = doler/herir
to take care of = cuidar
to protect = proteger
to prepare = preparar
to organize = organizar
to plan = planear/planificar
to reserve = reservar
to book = reservar
to rent = alquilar/rentar
to borrow = pedir prestado
to lend = prestar
to share = compartir
to exchange = cambiar/intercambiar
to order (food) = pedir
to serve = servir
to deliver = entregar
to fill out = rellenar/llenar
to sign = firmar
to print = imprimir
to copy = copiar
to download = descargar/bajar
to upload = subir
to search = buscar
to check = comprobar/revisar
to review = repasar/revisar
to practice = practicar
to improve = mejorar
to fail = fallar/suspender/reprobar
to pass (an exam) = aprobar
to translate = traducir
to spell = deletrear
to pronounce = pronunciar
to mean = significar
to correct = corregir
to finish (end) = acabar
to start (machine) = arrancar/encender
to turn on = encender/prender
to turn off = apagar
to connect = conectar
to charge = cargar
to fix (repair) = reparar
to knock = llamar/golpear
to ring = sonar
to sound = sonar
to dream = soñar
to imagine = imaginar
to guess = adivinar
to doubt = dudar
to wonder = preguntarse
to notice = notar/darse cuenta
to realize = darse cuenta
to recognize = reconocer
to compare = comparar
to describe = describir
to count on = contar con
to depend = depender
to return (something) = devolver
to accept = aceptar
to refuse = rechazar/negarse
to offer = ofrecer
to promise = prometer
to lie (untruth) = mentir
to steal = robar
to kill = matar
to fight = luchar/pelear
to shoot = disparar
to hide = esconder/esconderse
to escape = escapar/escaparse
to jump = saltar
to kick = patear/dar una patada
to hit = golpear/pegar
to smoke = fumar
to rain = llover
to snow = nevar
to shine = brillar
grandparents = abuelos
grandson = nieto
granddaughter = nieta
nephew = sobrino
niece = sobrina
brother-in-law = cuñado
sister-in-law = cuñada
father-in-law = suegro
mother-in-law = suegra
twin = gemelo/gemela/mellizo
neighbor = vecino/vecina
boss = jefe/jefa
colleague = colega/compañero
classmate = compañero de clase/compañera de clase
guest = invitado/huésped
stranger = desconocido/extraño
adult = adulto
teenager = adolescente
childhood = infancia/niñez
youth = juventud
old age = vejez
wedding = boda
marriage = matrimonio
divorce = divorcio
couple = pareja
single (unmarried) = soltero
married = casado
widow = viuda
dead = muerto
alive = vivo
birth = nacimiento
death = muerte
age = edad
waiter = camarero/mesero
cook = cocinero/cocinera
lawyer = abogado/abogada
engineer = ingeniero/ingeniera
nurse = enfermero/enfermera
police officer = policía
police = policía
firefighter = bombero
soldier = soldado
farmer = granjero/agricultor
driver = conductor/chófer
salesperson = vendedor/vendedora
writer = escritor/escritora
artist = artista
singer = cantante
actor = actor
actress = actriz
journalist = periodista
dentist = dentista
pharmacist = farmacéutico
pharmacy = farmacia
medicine = medicina/medicamento
pill = pastilla
pain = dolor
headache = dolor de cabeza
fever = fiebre
cold (illness) = resfriado/catarro
flu = gripe
cough = tos
blood = sangre
bone = hueso
skin = piel
neck = cuello
shoulder = hombro
elbow = codo
finger = dedo
knee = rodilla
chest = pecho
stomach = estómago/barriga
tongue = lengua
lip = labio
beard = barba
moustache = bigote
throat = garganta
toe = dedo del pie
brain = cerebro
appointment = cita
emergency = emergencia
accident = accidente
ambulance = ambulancia
help = ayuda
danger = peligro
dangerous = peligroso
safe = seguro
careful = cuidadoso
neighborhood = barrio
square (plaza) = plaza
corner = esquina
block (city) = manzana/cuadra
building = edificio
floor (storey) = piso/planta
stairs = escalera/escaleras
elevator = ascensor/elevador
entrance = entrada
exit = salida
museum = museo
library = biblioteca
bookstore = librería
bakery = panadería
butcher shop = carnicería
cinema = cine
theater = teatro
stadium = estadio
gym = gimnasio
swimming pool = piscina/alberca
post office = correos/oficina de correos
town hall = ayuntamiento
bridge = puente
tower = torre
castle = castillo
palace = palacio
village = aldea/pueblo
capital = capital
map = mapa
direction = dirección
address = dirección
north = norte
south = sur
east = este
west = oeste
traffic = tráfico
traffic light = semáforo
sidewalk = acera/banqueta
highway = autopista
parking lot = aparcamiento/estacionamiento
taxi = taxi
subway = metro
truck = camión
motorcycle = moto/motocicleta
ship = barco/buque
trip = viaje
journey = viaje
vacation = vacaciones
holiday (day off) = día festivo/feriado/fiesta
passport = pasaporte
suitcase = maleta
luggage = equipaje
tourist = turista
flight = vuelo
seat = asiento
platform = andén
round trip = ida y vuelta
one way = ida/solo ida
reservation = reserva/reservación
receipt = recibo
bill (restaurant) = cuenta
tip (money) = propina
price = precio
cash = efectivo
credit card = tarjeta de crédito
coin = moneda
change (money) = cambio/vuelto
discount = descuento
sale (discount) = rebajas/oferta
size = talla/tamaño
customer = cliente
menu = menú/carta
dessert = postre
cake = pastel/tarta/torta
cookie = galleta
ice cream = helado
chocolate = chocolate
candy = caramelo/dulce
butter = mantequilla
oil = aceite
vinegar = vinagre
pepper = pimienta
garlic = ajo
onion = cebolla
carrot = zanahoria
lettuce = lechuga
bean = frijol/judía/alubia
pea = guisante/chícharo
corn = maíz
mushroom = champiñón/seta/hongo
vegetable = verdura/vegetal
lemon = limón
grape = uva
strawberry = fresa
pear = pera
peach = melocotón/durazno
watermelon = sandía
pineapple = piña
cherry = cereza
pork = cerdo
beef = carne de res/ternera
ham = jamón
sausage = salchicha/chorizo
seafood = mariscos
shrimp = gamba/camarón
sandwich = bocadillo/sándwich
flour = harina
pasta = pasta
snack = merienda/tentempié/botana
meal = comida
hunger = hambre
thirst = sed
taste (flavor) = sabor
delicious = delicioso/rico
sweet = dulce
salty = salado
bitter = amargo
sour = agrio/ácido
spicy = picante
raw = crudo
cooked = cocido/cocinado
fresh = fresco
ripe = maduro
napkin = servilleta
fridge = nevera/refrigerador/frigorífico
oven = horno
stove = estufa/cocina
microwave = microondas
dishwasher = lavavajillas/lavaplatos
washing machine = lavadora
sink = fregadero/lavabo
shower = ducha/regadera
bathtub = bañera/tina
toilet = inodoro/váter/retrete
towel = toalla
soap = jabón
toothbrush = cepillo de dientes
toothpaste = pasta de dientes
mirror = espejo
sofa = sofá
armchair = sillón
lamp = lámpara
light = luz
closet = armario/clóset
drawer = cajón
shelf = estante/estantería
carpet = alfombra
curtain = cortina
pillow = almohada
blanket = manta/cobija
sheet (bed) = sábana
furniture = muebles
box = caja
basket = cesta/canasta
trash = basura
garage = garaje
balcony = balcón
yard = patio/jardín
ceiling = techo
rent = alquiler/renta
sock = calcetín
underwear = ropa interior
jacket = chaqueta/chamarra
sweater = suéter/jersey
jeans = vaqueros/jeans
boot = bota
sandal = sandalia
belt = cinturón
tie = corbata
scarf = bufanda
glove = guante
cap = gorra
glasses = gafas/lentes/anteojos
watch = reloj
clock = reloj
ring = anillo
necklace = collar
earring = pendiente/arete
umbrella = paraguas
wallet = cartera/billetera
purse = bolso/cartera
backpack = mochila
pocket = bolsillo
button = botón
fashion = moda
style = estilo
cotton = algodón
wool = lana
leather = cuero/piel
silk = seda
gold = oro
silver = plata
iron = hierro
wood = madera
glass (material) = vidrio/cristal
plastic = plástico
stone = piedra
sand = arena
earth = tierra
land = tierra
field = campo
countryside = campo
forest = bosque
jungle = selva
desert = desierto
island = isla
lake = lago
coast = costa
wave = ola
hill = colina/cerro
valley = valle
cloud = nube
storm = tormenta
lightning = rayo/relámpago
thunder = trueno
ice = hielo
fog = niebla
heat = calor
temperature = temperatura
degree = grado
sunny = soleado
cloudy = nublado
rainy = lluvioso
windy = ventoso
grass = hierba/césped/pasto
plant = planta
leaf = hoja
seed = semilla
pig = cerdo/cochino
sheep = oveja
goat = cabra
rabbit = conejo
mouse = ratón
rat = rata
lion = león
tiger = tigre
bear = oso
elephant = elefante
monkey = mono
snake = serpiente/culebra
duck = pato
hen = gallina
insect = insecto
fly (insect) = mosca
mosquito = mosquito
bee = abeja
spider = araña
butterfly = mariposa
ant = hormiga
pet = mascota
zoo = zoológico/zoo
hobby = afición/pasatiempo/hobby
team = equipo
player = jugador/jugadora
match (game) = partido
goal = gol/meta
race = carrera
tennis = tenis
basketball = baloncesto/básquetbol
swimming = natación
guitar = guitarra
piano = piano
drum = tambor
band (music) = banda/grupo
concert = concierto
dance = baile
photo = foto/fotografía
camera = cámara
picture (painting) = cuadro/pintura
painting = pintura/cuadro
newspaper = periódico/diario
magazine = revista
news = noticias
story = historia/cuento
tale = cuento
novel = novela
poem = poema
television show = programa
channel = canal
radio = radio
internet = internet
website = sitio web/página web
email = correo electrónico/correo/email
message = mensaje
screen = pantalla
keyboard = teclado
password = contraseña/clave
file = archivo
battery = batería/pila
noise = ruido
voice = voz
sound = sonido
silence = silencio
favorite = favorito/preferido
different = diferente/distinto
similar = similar/parecido
equal = igual
possible = posible
impossible = imposible
necessary = necesario
normal = normal
strange = raro/extraño
funny = gracioso/divertido
fun = divertido
serious = serio
quiet = tranquilo/callado
calm = tranquilo/calmado
nervous = nervioso
angry = enfadado/enojado
worried = preocupado
scared = asustado
surprised = sorprendido
bored = aburrido/aburrida
glad = alegre/contento
proud = orgulloso
shy = tímido
lazy = perezoso/flojo
hardworking = trabajador
brave = valiente
kind = amable
polite = educado/cortés
rude = maleducado/grosero
honest = honesto/honrado
crazy = loco
strong = fuerte
weak = débil
fat = gordo
thin = delgado/flaco
heavy = pesado
light (weight) = ligero/liviano
soft = suave/blando
hard = duro
wet = mojado
dry = seco
warm = cálido/tibio
cool = fresco
dark = oscuro
bright = brillante/luminoso
loud = fuerte/ruidoso
deep = profundo
wide = ancho
narrow = estrecho/angosto
round = redondo
square (shape) = cuadrado
flat = plano
straight = recto/derecho
broken = roto
correct = correcto
wrong = incorrecto/equivocado
famous = famoso
popular = popular
modern = moderno
ancient = antiguo
traditional = tradicional
typical = típico
public = público
private = privado
own = propio
whole = entero/todo
alone = solo/sola
together = juntos/juntas
enough = bastante/suficiente
too much = demasiado
almost = casi
maybe = quizás/quizá/tal vez/a lo mejor
perhaps = quizás/quizá/tal vez
of course = claro/por supuesto
really = de verdad/realmente
quickly = rápidamente/rápido
slowly = despacio/lentamente
usually = normalmente/generalmente
sometimes = a veces
often = a menudo/muchas veces/con frecuencia
every day = todos los días/cada día
once = una vez
twice = dos veces
ago = hace
yet (not yet) = todavía/aún
since = desde
while = mientras
although = aunque
so (therefore) = así que/por eso/entonces
anyway = de todos modos/de todas formas
especially = especialmente/sobre todo
however = sin embargo
instead of = en vez de/en lugar de
according to = según
against = contra
toward = hacia
across = a través de
around = alrededor
through = por/a través de
above = encima/arriba
below = debajo/abajo
everywhere = en todas partes/por todas partes
somewhere = en algún lugar/en alguna parte
nowhere = en ningún lugar/en ninguna parte
anything = cualquier cosa/algo/nada
everyone = todos/todo el mundo
some = algunos/algunas/unos/unas
any = cualquier/algún/ningún
none = ninguno/ninguna
both = ambos/los dos
several = varios/varias
many = muchos/muchas
few = pocos/pocas
another = otro/otra
such = tal
past = pasado
present = presente
future = futuro
date = fecha
calendar = calendario
schedule = horario
day off = día libre
midnight = medianoche
noon = mediodía
dawn = amanecer/madrugada
century = siglo
decade = década
last night = anoche
the day before yesterday = anteayer/antier
the day after tomorrow = pasado mañana
next week = la semana que viene/la próxima semana
o'clock = en punto
quarter = cuarto
`);
