addWords("B2", `
to acknowledge = reconocer
to adapt = adaptar/adaptarse
to adjust = ajustar
to affect = afectar
to afford (time) = permitirse
to approach = acercarse/aproximarse
to approve = aprobar
to arise = surgir
to arrange = organizar/arreglar/ordenar
to assess = evaluar/valorar
to assign = asignar
to assure = asegurar
to attempt = intentar/tratar
to attract = atraer
to bear (tolerate) = soportar/aguantar
to beat = vencer/batir/golpear
to beg = rogar/suplicar/mendigar
to behave well = portarse bien
to boast = presumir/jactarse
to borrow money = pedir dinero prestado
to bounce = rebotar
to breed = criar
to bury = enterrar
to calm = calmar/tranquilizar
to capture = capturar
to cease = cesar
to challenge = desafiar/retar
to claim = afirmar/reclamar
to clarify = aclarar
to collapse = derrumbarse/colapsar
to commit = cometer/comprometerse
to communicate = comunicar/comunicarse
to complete = completar
to conclude = concluir
to condemn = condenar
to confess = confesar
to confront = enfrentar/enfrentarse
to confuse = confundir
to congratulate = felicitar
to conquer = conquistar
to consist of = consistir en
to consume = consumir
to contain = contener
to contribute = contribuir/aportar
to convince = convencer
to cooperate = cooperar/colaborar
to cope = arreglárselas/hacer frente
to criticize = criticar
to dedicate = dedicar
to define = definir
to delay (postpone) = aplazar
to demonstrate = demostrar
to depend on = depender de
to determine = determinar
to devote = dedicar
to disagree = no estar de acuerdo/discrepar
to disappear = desaparecer
to disappoint = decepcionar
to dislike = no gustar/desagradar
to distinguish = distinguir
to distribute = distribuir/repartir
to disturb = molestar/perturbar
to earn respect = ganarse el respeto
to emphasize = enfatizar/destacar/subrayar
to employ = emplear
to enable = permitir/posibilitar
to encourage = animar/fomentar
to endure = soportar/aguantar
to engage = comprometerse/involucrarse
to enhance = mejorar/realzar
to ensure = asegurar/garantizar
to establish = establecer
to evaluate = evaluar
to evolve = evolucionar
to exaggerate = exagerar
to examine = examinar
to exceed = superar/exceder
to exclude = excluir
to excuse = excusar/disculpar
to expand = ampliar/expandir
to experience = experimentar/vivir
to exploit = explotar
to export = exportar
to import = importar
to expose = exponer
to extend = extender/ampliar
to face = enfrentar/afrontar
to fade = desvanecerse/desteñirse
to fascinate = fascinar
to fear = temer
to flee = huir
to focus = enfocar/centrarse
to forecast = pronosticar/prever
to found = fundar
to frustrate = frustrar
to gain = ganar/obtener
to generate = generar
to grant = conceder/otorgar
to guarantee = garantizar
to handle = manejar
to harm = dañar/perjudicar
to hate = odiar
to highlight = destacar/resaltar
to identify = identificar
to illustrate = ilustrar
to impose = imponer
to impress = impresionar
to indicate = indicar
to influence = influir/influenciar
to inherit = heredar
to injure oneself = lastimarse/hacerse daño
to inspire = inspirar
to intend = pretender/tener la intención
to interpret = interpretar
to interrupt = interrumpir
to introduce (person) = presentar
to introduce (bring in) = introducir
to involve = implicar/involucrar
to justify = justificar
to lack (be short of) = carecer de
to launch = lanzar
to lean = apoyarse/inclinarse
to limit = limitar
to maintain (claim) = sostener/afirmar
to manufacture = fabricar
to mark = marcar
to mislead = engañar
to modify = modificar
to motivate = motivar
to negotiate = negociar
to neglect = descuidar
to observe = observar
to obtain = obtener/conseguir
to occupy = ocupar
to occur = ocurrir/suceder
to oppose = oponerse
to overcome = superar/vencer
to owe money = deber dinero
to perceive = percibir
to perform = realizar/actuar/interpretar
to persuade = persuadir/convencer
to possess = poseer
to praise = elogiar/alabar
to pray = rezar/orar
to prevent = prevenir/impedir/evitar
to proceed = proceder
to promote = promover/promocionar/ascender
to provide = proporcionar/proveer/dar
to provoke = provocar
to pursue = perseguir/seguir
to qualify = calificar/clasificarse
to react = reaccionar
to rebel = rebelarse
to recall = recordar
to reconcile = reconciliar/reconciliarse
to recover (get back) = recuperar
to reflect on = reflexionar sobre
to reform = reformar
to regard = considerar
to reject = rechazar
to relate = relacionar
to release = liberar/soltar/lanzar
to rely on = depender de/contar con/confiar en
to remark = comentar/observar
to remind = recordar
to repeat oneself = repetirse
to replace (substitute) = sustituir
to represent = representar
to rescue = rescatar
to resist = resistir/resistirse
to resolve = resolver
to respond = responder
to restrict = restringir
to reward = recompensar/premiar
to risk = arriesgar
to satisfy = satisfacer
to scream = gritar/chillar
to seek = buscar
to seize = agarrar/apoderarse
to settle = establecerse/instalarse/resolver
to shelter = refugiarse/proteger
to shift = cambiar/desplazar
to simplify = simplificar
to slip = resbalar/resbalarse
to solve (a problem) = solucionar
to spoil = estropear/mimar
to stand (tolerate) = soportar/aguantar
to stare = mirar fijamente
to starve = morir de hambre
to strengthen = fortalecer/reforzar
to stress (emphasize) = recalcar/subrayar
to struggle = luchar/esforzarse
to submit = presentar/entregar/someter
to succeed = tener éxito/triunfar
to summarize = resumir
to supply = suministrar/abastecer
to surround = rodear
to survive = sobrevivir
to suspect = sospechar
to sustain = sostener/mantener
to swallow = tragar
to swear = jurar
to take place = tener lugar/ocurrir
to tease = burlarse/tomar el pelo
to tolerate = tolerar
to transform = transformar
to transmit = transmitir
to transport = transportar
to trap = atrapar
to undergo = someterse/sufrir
to undertake = emprender
to unite = unir
to urge = instar/urgir
to value = valorar
to vary = variar
to violate = violar
to wander = vagar/deambular
to weaken = debilitar
to wipe = limpiar/secar
to withdraw = retirar/retirarse/sacar
to witness = presenciar/ser testigo
to yield = ceder/rendir
to yawn = bostezar
to sneeze = estornudar
to blink = parpadear
to nod = asentir
to sigh = suspirar
to frown = fruncir el ceño
to whistle = silbar
to chew = masticar
to bite = morder
to lick = lamer
to scratch = rascar/arañar
to pinch = pellizcar
to tickle = hacer cosquillas
to stumble = tropezar
to crawl = gatear/arrastrarse
to kneel = arrodillarse
to lean on = apoyarse en
to rush = apresurarse/precipitarse
to wander around = dar vueltas/pasear
to stroll = pasear/dar un paseo
to take a walk = dar un paseo/pasear
to hike = hacer senderismo/caminar
to skate = patinar
to ski = esquiar
to dive = bucear/zambullirse
to row = remar
to camp = acampar
to sunbathe = tomar el sol
to get a tan = broncearse/ponerse moreno
to get dressed = vestirse
to get undressed = desvestirse/desnudarse
to make up (invent) = inventar
to make up (reconcile) = hacer las paces/reconciliarse
to put up with = aguantar/soportar
to look forward to = tener ganas de/esperar con ilusión
to run out of = quedarse sin/acabarse
to give up = rendirse/renunciar/dejar
to give back = devolver
to find out = averiguar/enterarse/descubrir
to figure out = averiguar/entender
to point out = señalar
to carry out = llevar a cabo/realizar
to set up = establecer/montar
to break down (machine) = averiarse/estropearse
to turn down (refuse) = rechazar
to turn up (volume) = subir
to turn down (volume) = bajar
to show up = aparecer/presentarse
to take over = hacerse cargo/tomar el control
to look after = cuidar
to get rid of = deshacerse de/librarse de
to keep going = seguir adelante
to come up with = idear/ocurrirse
to be about to = estar a punto de
to have just = acabar de
to stop doing = dejar de
to start doing = empezar a/ponerse a
to be worth it = valer la pena
to make a mistake = equivocarse/cometer un error
to pay a visit = hacer una visita
to make a decision = tomar una decisión
to take a photo = sacar una foto/hacer una foto/tomar una foto
to take notes = tomar apuntes/tomar notas
to pay attention to = prestar atención a/hacer caso a
to make fun of = burlarse de/reírse de
to be in charge of = estar a cargo de/encargarse de
to keep in mind = tener en cuenta
to take into account = tener en cuenta
to feel like = tener ganas de/apetecer
to be fed up = estar harto
to be in a good mood = estar de buen humor
to be in a bad mood = estar de mal humor
to be broke = estar sin blanca/estar sin dinero
to be lucky enough = tener la suerte
to fall asleep = dormirse/quedarse dormido
to oversleep = quedarse dormido
to sleep in = dormir hasta tarde
to stay up late = trasnochar/quedarse despierto
to fall behind = quedarse atrás/atrasarse
to catch up = ponerse al día/alcanzar
to warn someone = avisar
to look up (a word) = buscar
to hang out = salir/pasar el rato
to hang up (phone) = colgar
to pick up (phone) = contestar/coger
to leave a message = dejar un mensaje
to run into = encontrarse con/toparse con
to get together = reunirse/quedar
to arrange to meet = quedar
to show off = presumir/lucirse
achievement = logro
acquaintance = conocido/conocida
activity = actividad
addiction = adicción
adult life = vida adulta
agency = agencia
aim = objetivo/meta/propósito
alarm = alarma
alliance = alianza
ambition = ambición
amusement = diversión/entretenimiento
analysis = análisis
announcement = anuncio
anniversary = aniversario
appearance = apariencia/aspecto/aparición
application (job) = solicitud
approach = enfoque/acercamiento
approval = aprobación
architecture = arquitectura
arrangement = arreglo/acuerdo
aspect = aspecto
assessment = evaluación/valoración
assumption = suposición
atmosphere = ambiente/atmósfera
attempt = intento
attitude = actitud
authority = autoridad
average = promedio/media
awareness = conciencia/concienciación
balance = equilibrio/balance/saldo
barrier = barrera
basis = base
behaviour (manners) = modales
bond = vínculo/lazo
boundary = límite/frontera
branch = rama/sucursal
breakthrough = avance/descubrimiento
breath = aliento/respiración
burden = carga
campaign = campaña
candidate = candidato/candidata
capacity = capacidad
category = categoría
challenge = desafío/reto
change (alteration) = cambio
charity = caridad/organización benéfica
circumstance = circunstancia
claim = reclamación/afirmación
clue = pista
code = código
commitment = compromiso
committee = comité
comparison = comparación
competition = competencia/competición/concurso
complaint = queja/reclamación
concept = concepto
concern = preocupación
conclusion = conclusión
condition = condición
conflict = conflicto
confidence = confianza/seguridad
consciousness = conciencia
content = contenido
context = contexto
contribution = contribución/aportación
convenience = comodidad/conveniencia
conviction = convicción
corruption = corrupción
courage = valor/valentía/coraje
coward = cobarde
creature = criatura
crisis = crisis
criticism = crítica
cure = cura
curiosity = curiosidad
damage = daño/daños
deadline = plazo/fecha límite
deal = trato/acuerdo
debate = debate
defence = defensa
definition = definición
degree (extent) = grado
demand = demanda/exigencia
departure (leaving) = partida
desire = deseo
despair = desesperación
destiny = destino
development = desarrollo
difference = diferencia
difficulty = dificultad
dignity = dignidad
dilemma = dilema
dimension = dimensión
disappointment = decepción/desilusión
discipline = disciplina
discrimination = discriminación
dispute = disputa/conflicto
distinction = distinción
diversity = diversidad
doubt = duda
draft = borrador
drawing = dibujo
duty (obligation) = obligación
education = educación
efficiency = eficiencia
element = elemento
emphasis = énfasis
employee = empleado/empleada
employer = empleador/empleadora
employment = empleo
encounter = encuentro
encouragement = ánimo/aliento
engagement = compromiso
entertainment = entretenimiento
enthusiasm = entusiasmo
entry = entrada
equality = igualdad
equipment = equipo/equipamiento
essay = ensayo/redacción
essence = esencia
estimate = estimación/presupuesto
ethics = ética
evolution = evolución
exception = excepción
excuse = excusa
existence = existencia
expectation = expectativa
expense = gasto
expert = experto/experta
explanation = explicación
expression = expresión
extent = alcance/medida
failure (breakdown) = fallo/avería
faith (trust) = confianza
fame = fama
fault = culpa/defecto/falta
favour = favor
feature = característica/rasgo
fee = tarifa/cuota/honorarios
fiction = ficción
figure (number) = cifra
finding = hallazgo
flavour = sabor
flaw = defecto/fallo
focus = enfoque/foco
fortune = fortuna
foundation = fundación/base/cimientos
framework = marco
frequency = frecuencia
function = función
funds = fondos
gap = hueco/brecha/espacio
gender = género
genius = genio
gesture = gesto
goodness = bondad
grief = dolor/pena/duelo
growth = crecimiento
guilt = culpa
harm = daño
harmony = armonía
hatred = odio
heritage = patrimonio/herencia
hint = pista/indirecta
honour = honor
horror = horror
hospitality = hospitalidad
humour = humor
hypothesis = hipótesis
identity = identidad
illusion = ilusión
impact = impacto
impression = impresión
improvement = mejora
incident = incidente
independence = independencia
individual = individuo
inequality = desigualdad
influence = influencia
injustice = injusticia
innovation = innovación
insight = perspicacia/comprensión
instance = caso/ejemplo
instinct = instinto
institution = institución
instruction = instrucción
insult = insulto
insurance = seguro
intelligence = inteligencia
intention = intención
interest = interés
issue = asunto/tema/problema
journalism = periodismo
judgement = juicio
kindness = amabilidad/bondad
labour = trabajo/mano de obra
lack = falta/carencia
landlord = casero/propietario
leadership = liderazgo
legacy = legado
leisure = ocio
liberty = libertad
lifestyle = estilo de vida
limit = límite
literature = literatura
loneliness = soledad
loyalty = lealtad
majority = mayoría
minority = minoría
management = gestión/dirección
manner = manera/modo
mass = masa
measure = medida
mechanism = mecanismo
mention = mención
merit = mérito
mess = desorden/lío
mission = misión
mixture = mezcla
motive = motivo
movement = movimiento
myth = mito
necessity = necesidad
need = necesidad
negotiation = negociación
nonsense = tontería/disparate
notion = noción
objective = objetivo
obligation = obligación
obstacle = obstáculo
occasion = ocasión
offence = delito/ofensa
offer = oferta
operation = operación
opponent = oponente/adversario
opposition = oposición
order (command) = orden
order (sequence) = orden
organization = organización
origin = origen
outcome = resultado
pace = ritmo/paso
pattern = patrón/modelo
peak = cima/pico
penalty = pena/sanción/penalti
perception = percepción
performance = rendimiento/actuación
period = período/periodo/época
permission = permiso
perspective = perspectiva
phenomenon = fenómeno
philosophy = filosofía
pity = lástima/pena
position = posición/puesto
possibility = posibilidad
poverty = pobreza
wealth = riqueza
practice = práctica
praise = elogio/alabanza
prejudice = prejuicio
presence = presencia
pressure = presión
prevention = prevención
principle = principio
priority = prioridad
privacy = privacidad/intimidad
privilege = privilegio
procedure = procedimiento
profession = profesión
progress = progreso/avance
promise = promesa
proof = prueba
property = propiedad
proportion = proporción
prosperity = prosperidad
protection = protección
protest = protesta
psychology = psicología
punishment = castigo
qualification = cualificación/título
range = rango/gama/variedad
rate = tasa/índice/ritmo
reaction = reacción
reality = realidad
recognition = reconocimiento
recommendation = recomendación
reference = referencia
reform = reforma
refugee = refugiado/refugiada
regret = arrepentimiento/pesar
relief = alivio
reputation = reputación/fama
requirement = requisito
resident = residente
resource = recurso
response = respuesta
responsibility = responsabilidad
revenge = venganza
revolution = revolución
reward = recompensa/premio
role = papel/rol
routine = rutina
safety = seguridad
satisfaction = satisfacción
scale = escala
scandal = escándalo
scheme = plan/esquema
security = seguridad
selection = selección
sensation = sensación
sequence = secuencia
series = serie
settlement = asentamiento/acuerdo
shortage = escasez/falta
significance = importancia/significado
situation = situación
solidarity = solidaridad
source = fuente/origen
spending = gasto
stability = estabilidad
standard = nivel/estándar/norma
statement = declaración/afirmación
status = estatus/estado/condición
strategy = estrategia
structure = estructura
struggle = lucha
subject (topic) = tema/asunto
substance = sustancia
suffering = sufrimiento
summary = resumen
supply = suministro/oferta
support = apoyo
surface = superficie
survey = encuesta
survival = supervivencia
suspicion = sospecha
sympathy = compasión/comprensión
talent = talento
target = objetivo/meta/blanco
task = tarea
tendency = tendencia
tension = tensión
territory = territorio
theme = tema
theory = teoría
threat = amenaza
tolerance = tolerancia
topic = tema
trade = comercio
trend = tendencia/moda
trick = truco/trampa
trouble = problema/lío
uncertainty = incertidumbre
understanding = comprensión/entendimiento
unemployment = desempleo/paro
union = unión/sindicato
unity = unidad
value = valor
variety = variedad
version = versión
violence = violencia
virtue = virtud
vision = visión
volunteer = voluntario/voluntaria
warning = aviso/advertencia
waste = desperdicio/residuos
welfare = bienestar
well-being = bienestar
will (desire) = voluntad
wisdom = sabiduría
worker = trabajador/trabajadora
worry = preocupación
youth (young people) = jóvenes/juventud
ankle = tobillo
wrist = muñeca
hip = cadera
waist = cintura
thumb = pulgar
nail = uña
eyebrow = ceja
eyelash = pestaña
cheek = mejilla
chin = barbilla/mentón
forehead = frente
jaw = mandíbula
lung = pulmón
liver = hígado
kidney = riñón
muscle = músculo
vein = vena
sweat = sudor
tear (crying) = lágrima
scar = cicatriz
bruise = moretón/moratón
wrinkle = arruga
allergy = alergia
infection = infección
virus = virus
cancer = cáncer
diabetes = diabetes
heart attack = infarto/ataque al corazón
stroke = derrame cerebral/ictus
prescription = receta
dose = dosis
side effect = efecto secundario
recovery = recuperación
cast (medical) = escayola/yeso
crutches = muletas
wheelchair = silla de ruedas
consultation = consulta
clinic = clínica
check-up = revisión/chequeo
bandage = venda/vendaje
plaster (band-aid) = tirita/curita
needle = aguja
thread = hilo
scissors = tijeras
hammer = martillo
nail (metal) = clavo
screw = tornillo
rope = cuerda
chain = cadena
ladder = escalera de mano
bucket = cubo/balde
brush = cepillo/pincel
broom = escoba
sponge = esponja
lid = tapa
jar = tarro/frasco
can (tin) = lata
pan = sartén/cazuela
pot = olla/maceta
tray = bandeja
kettle = hervidor/tetera
corkscrew = sacacorchos
recipe = receta
ingredient = ingrediente
slice = rebanada/loncha/rodaja
piece = pedazo/trozo/pieza
crumb = miga
grain = grano
nut = nuez/fruto seco
almond = almendra
olive = aceituna/oliva
cucumber = pepino
pumpkin = calabaza
spinach = espinaca/espinacas
cabbage = col/repollo
cauliflower = coliflor
eggplant = berenjena
zucchini = calabacín
avocado = aguacate/palta
coconut = coco
plum = ciruela
melon = melón
raspberry = frambuesa
honey = miel
jam = mermelada
cream = nata/crema
yogurt = yogur
tuna = atún
salmon = salmón
lamb = cordero
turkey = pavo
steak = filete/bistec
roast = asado
stew = guiso/estofado
grilled = a la plancha/a la parrilla
fried = frito
boiled = hervido/cocido
baked = al horno/horneado
frozen = congelado
tasty = sabroso/rico
bland = soso/insípido
appetite = apetito
vegetarian = vegetariano/vegetariana
vegan = vegano/vegana
waiter (female) = camarera/mesera
tip (advice) = consejo
counter = mostrador
queue = cola/fila
trolley = carrito
aisle = pasillo
corridor = pasillo
hall = vestíbulo/salón
basement = sótano
attic = ático/desván
fence = valla/cerca
gate = puerta/portón/verja
lawn = césped
pond = estanque
fountain = fuente
statue = estatua
monument = monumento
cathedral = catedral
mosque = mezquita
temple = templo
cemetery = cementerio
ruins = ruinas
harbour = puerto
lighthouse = faro
cliff = acantilado
peninsula = península
tide = marea
current (water) = corriente
stream = arroyo
waterfall = cascada/catarata
swamp = pantano
meadow = prado
branch (tree) = rama
root = raíz
trunk = tronco
bush = arbusto
rose = rosa
pine = pino
oak = roble
palm tree = palmera
wolf = lobo
fox = zorro
deer = ciervo/venado
squirrel = ardilla
whale = ballena
dolphin = delfín
shark = tiburón
turtle = tortuga
frog = rana
crocodile = cocodrilo
eagle = águila
owl = búho/lechuza
parrot = loro
pigeon = paloma
seagull = gaviota
worm = gusano
snail = caracol
cockroach = cucaracha
donkey = burro/asno
bull = toro
ox = buey
camel = camello
giraffe = jirafa
zebra = cebra
kangaroo = canguro
feather = pluma
wing = ala
tail = cola/rabo
claw = garra
fur = pelaje/piel
nest = nido
cage = jaula
herd = manada/rebaño
cattle = ganado
agriculture = agricultura
tractor = tractor
soil = suelo/tierra
dew = rocío
breeze = brisa
hail = granizo
frost = escarcha/helada
humidity = humedad
forecast = pronóstico
rainbow = arcoíris
climate crisis = crisis climática
heatwave = ola de calor
global warming = calentamiento global
renewable = renovable
solar panel = panel solar
species = especie
extinction = extinción
habitat = hábitat
resident (local) = vecino
mayor = alcalde/alcaldesa
council = consejo/ayuntamiento
parliament = parlamento
senate = senado
congress = congreso
constitution = constitución
republic = república
dictatorship = dictadura
monarchy = monarquía
empire = imperio
colony = colonia
independence day = día de la independencia
regime = régimen
reform (change) = reforma
strike (work) = huelga
demonstration (protest) = manifestación
riot = disturbio/motín
terrorism = terrorismo
kidnapping = secuestro
fraud = fraude
bribe = soborno
lawsuit = demanda/pleito
sentence (court) = sentencia/condena
sentence (grammar) = oración/frase
verdict = veredicto
lawyer (attorney) = abogado
attorney = abogado/abogada/fiscal
prosecutor = fiscal
suspect = sospechoso/sospechosa
detective = detective
investigation = investigación
guard = guardia/vigilante
spy = espía
soldier (troop) = tropa
navy = marina/armada
air force = fuerza aérea
treaty = tratado
invasion = invasión
refuge = refugio
shelter = refugio/albergue
stock market = bolsa
share (stock) = acción
investment = inversión
interest (bank) = interés
mortgage = hipoteca
savings = ahorros
pension = pensión
retirement = jubilación
wage = salario/sueldo
raise (salary) = aumento
bonus = prima/bonificación
shift (work) = turno
overtime = horas extra/horas extras
staff = personal/plantilla
manager = gerente/director/encargado
director = director/directora
chairman = presidente
shareholder = accionista
client = cliente/clienta
supplier = proveedor
competitor = competidor/competencia
headquarters = sede
branch office = sucursal
warehouse = almacén
invoice = factura
order (purchase) = pedido
delivery = entrega/reparto
shipment = envío
stock = existencias/stock
sample = muestra
brand new = nuevo/flamante
second-hand = de segunda mano/usado
guarantee = garantía
refund = reembolso/devolución
complaint form = hoja de reclamaciones
advertising = publicidad
marketing = marketing/mercadotecnia
consumer = consumidor/consumidora
purchase = compra
bargain = ganga/chollo
luxury = lujo
poverty line = umbral de pobreza
homeless = sin hogar/sin techo
charity (organization) = organización benéfica/ONG
donation = donación/donativo
volunteer work = voluntariado
nursery = guardería
kindergarten = jardín de infancia/kínder
primary school = escuela primaria/primaria
high school = instituto/secundaria/preparatoria
college = universidad/facultad
faculty = facultad
scholarship = beca
tuition = matrícula
lecture = clase/conferencia
lecturer = profesor universitario/profesora universitaria
thesis = tesis
dissertation = tesina/tesis
graduation = graduación
graduate = graduado/licenciado
master's degree = máster/maestría
doctorate = doctorado
notes (class) = apuntes
textbook = libro de texto
dictionary = diccionario
grammar = gramática
vocabulary = vocabulario
pronunciation = pronunciación
spelling = ortografía
accent = acento
fluent = fluido/con fluidez
bilingual = bilingüe
native speaker = hablante nativo/nativo
translation = traducción
translator = traductor/traductora
interpreter = intérprete
paragraph = párrafo
sentence = frase/oración
phrase = frase/expresión
verb = verbo
noun = sustantivo/nombre
adjective = adjetivo
plural = plural
singular = singular
masculine = masculino
feminine = femenino
tense = tiempo verbal/tiempo
mathematics = matemáticas
physics = física
chemistry = química
biology = biología
geography = geografía
economics = economía
law (subject) = derecho
medicine (field) = medicina
engineering = ingeniería
philosophy (subject) = filosofía
painting (art) = pintura
sculpture = escultura
poetry = poesía
theatre play = obra de teatro/obra
plot = trama/argumento
ending = final/desenlace
main character = protagonista
review (critique) = reseña/crítica
critic = crítico/crítica
masterpiece = obra maestra
gallery = galería
exhibition hall = sala de exposiciones
rehearsal = ensayo
audition = audición/prueba
applause = aplauso/aplausos
award = premio/galardón
prize = premio
trophy = trofeo
championship = campeonato
tournament = torneo
league = liga
coach = entrenador/entrenadora
referee = árbitro
score (points) = puntuación/marcador
draw (tie) = empate
fan (supporter) = hincha/aficionado
athlete = atleta/deportista
cycling = ciclismo
skiing = esquí
hiking = senderismo
climbing = escalada
fishing = pesca
hunting = caza
chess = ajedrez
cards (game) = cartas/naipes
dice = dados
puzzle = rompecabezas/puzle
toy = juguete
doll = muñeca
kite = cometa/papalote
swing = columpio
slide (playground) = tobogán
playground = parque infantil
software = software
hardware = hardware
device (gadget) = aparato
charger = cargador
plug = enchufe
cable = cable
wire = alambre/cable
signal (phone) = señal/cobertura
coverage = cobertura
screen (display) = pantalla
mouse (computer) = ratón
printer = impresora
folder = carpeta
attachment = archivo adjunto/adjunto
inbox = bandeja de entrada
spam = correo basura/spam
search engine = buscador/motor de búsqueda
username = nombre de usuario
profile = perfil
privacy settings = configuración de privacidad
update = actualización
virus (computer) = virus
hacker = hacker/pirata informático
robot = robot
artificial intelligence = inteligencia artificial
digital = digital
online = en línea/online
wireless = inalámbrico
abroad = en el extranjero/al extranjero
accurate = preciso/exacto
acceptable = aceptable
adequate = adecuado/suficiente
aggressive = agresivo
alike = parecido/igual
annoying = molesto/pesado/fastidioso
anxious = ansioso/preocupado
apparent = aparente/evidente
appropriate = apropiado/adecuado
ashamed = avergonzado
attractive = atractivo
aware = consciente
awkward = incómodo/torpe
bold = audaz/atrevido
brief = breve
brilliant = brillante/genial
broad = amplio/ancho
careless = descuidado
cautious = cauteloso/prudente
cheerful = alegre
clumsy = torpe
competent = competente
complete = completo
concerned = preocupado
confident = seguro/seguro de sí mismo
conscious = consciente
considerable = considerable
consistent = coherente/constante
convenient = conveniente/práctico
cruel = cruel
cute = mono/lindo/tierno
decent = decente
delighted = encantado
dependent = dependiente
desperate = desesperado
determined = decidido/determinado
eager = ansioso/deseoso
efficient = eficiente/eficaz
elderly = anciano/mayor
elegant = elegante
emotional = emocional/emotivo
essential = esencial/imprescindible
evil = malvado/malo
evident = evidente
exhausted = agotado/exhausto
extraordinary = extraordinario
extreme = extremo
faithful = fiel
familiar = familiar/conocido
fierce = feroz
flexible = flexible
foolish = tonto/insensato
fortunate = afortunado
frank = franco/sincero
frightened = asustado
furious = furioso
gentle = suave/amable/delicado
genuine = auténtico/genuino
gorgeous = precioso/guapísimo
handsome = guapo
pretty (person) = guapa/bonita
harmful = dañino/perjudicial
harsh = duro/severo
helpful = útil/servicial
helpless = indefenso
hidden = oculto/escondido
humble = humilde
ideal = ideal
ill = enfermo/mal
immense = inmenso
impatient = impaciente
impressive = impresionante
inevitable = inevitable
initial = inicial
intense = intenso
keen = entusiasta/interesado
legitimate = legítimo
liberal = liberal
logical = lógico
loyal = leal/fiel
mad = loco/enfadado
marvellous = maravilloso
mean (unkind) = mezquino/malo/tacaño
mere = mero/simple
messy = desordenado
minor = menor/pequeño
miserable = triste/desgraciado
moderate = moderado
modest = modesto
moral = moral
mysterious = misterioso
naked = desnudo
narrow-minded = cerrado/estrecho de miras
naughty = travieso
neat = ordenado/pulcro
negative = negativo
positive = positivo
neutral = neutral/neutro
noble = noble
numerous = numeroso
odd = raro/extraño/impar
offended = ofendido
optimistic = optimista
pessimistic = pesimista
ordinary = corriente/normal/común
outstanding = destacado/excelente
overweight = con sobrepeso/gordo
painful = doloroso
peaceful = tranquilo/pacífico
precious = precioso/valioso
precise = preciso
pregnant (expecting) = embarazada/esperando
primary = primario/principal
prior = previo/anterior
productive = productivo
profound = profundo
promising = prometedor
proper = apropiado/adecuado/correcto
pure = puro
radical = radical
rapid = rápido
rational = racional
raw (unprocessed) = bruto/crudo
relaxed = relajado
relevant = relevante/pertinente
reliable = fiable/confiable
remarkable = notable/extraordinario
remote = remoto/lejano
reserved = reservado
respectful = respetuoso
rough = áspero/duro/aproximado
royal = real
sacred = sagrado
scarce = escaso
secure = seguro
severe = grave/severo
sharp = afilado/agudo
shocked = conmocionado/impactado
significant = significativo/importante
sincere = sincero
skilled = hábil/cualificado
smooth = liso/suave
sober = sobrio
solid = sólido
spare = de repuesto/libre
spectacular = espectacular
spontaneous = espontáneo
stable = estable
steady = constante/firme/estable
sticky = pegajoso
stiff = rígido/tieso
strict = estricto
stubborn = terco/testarudo/cabezota
subtle = sutil
sudden = repentino/súbito
sufficient = suficiente
suitable = adecuado/apropiado
superb = magnífico/excelente
superior = superior
suspicious = sospechoso/desconfiado
talented = talentoso/con talento
tender = tierno
tense (nervous) = tenso
thick = grueso/espeso
thin (flat) = fino/delgado
thorough = minucioso/exhaustivo
tight = apretado/ajustado
tough = duro/resistente
toxic = tóxico
tremendous = tremendo/enorme
tricky = difícil/complicado/delicado
ultimate = último/definitivo
unaware = inconsciente/ignorante
unbelievable = increíble
uncertain = incierto/inseguro
unexpected = inesperado
unfortunate = desafortunado/lamentable
unknown = desconocido
unusual = inusual/poco común/raro
upper = superior
urgent = urgente
vague = vago/impreciso
vain = vanidoso/vano
valid = válido
various = varios/diversos
vast = vasto/inmenso
violent = violento
visible = visible
vital = vital/esencial
vivid = vivo/vívido
vulnerable = vulnerable
weird = raro/extraño
wicked = malvado
wild = salvaje/silvestre
willing = dispuesto
witty = ingenioso/gracioso
worthy = digno
accordingly = en consecuencia
admittedly = es cierto que/hay que reconocer que
altogether = en total/del todo
apparently = al parecer/aparentemente
approximately = aproximadamente
barely = apenas
basically = básicamente
beforehand = de antemano/con antelación
consequently = por consiguiente/en consecuencia
constantly = constantemente
deliberately = deliberadamente/a propósito
directly = directamente
easily = fácilmente
entirely = enteramente/completamente
equally = igualmente
eventually = finalmente/al final/con el tiempo
evidently = evidentemente
extremely = extremadamente/sumamente
fairly = bastante/justamente
fortunately = afortunadamente/por suerte
unfortunately = desafortunadamente/por desgracia/lamentablemente
frankly = francamente
gradually = gradualmente/poco a poco
hence = por lo tanto/de ahí
highly = altamente/sumamente
honestly = honestamente/sinceramente
hopefully = ojalá/con suerte
increasingly = cada vez más
indeed (really) = realmente
instead = en cambio/en su lugar
largely = en gran parte/mayormente
literally = literalmente
mainly = principalmente/sobre todo
merely = simplemente/meramente
mostly = mayormente/sobre todo
naturally = naturalmente
necessarily = necesariamente
nevertheless = sin embargo/no obstante
nonetheless = no obstante
normally = normalmente
notably = notablemente
occasionally = ocasionalmente/de vez en cuando
partly = en parte
personally = personalmente
possibly = posiblemente
precisely = precisamente
presumably = presumiblemente/supuestamente
previously = previamente/anteriormente
primarily = principalmente
properly = correctamente/bien
rarely = raramente/rara vez
readily = fácilmente/de buena gana
relatively = relativamente
reluctantly = de mala gana/a regañadientes
roughly = aproximadamente
seldom = rara vez/casi nunca
seriously = seriamente/en serio
significantly = significativamente
similarly = de manera similar/igualmente
simply = simplemente
somehow = de alguna manera/de algún modo
somewhat = algo/un tanto
specifically = específicamente
strictly = estrictamente
supposedly = supuestamente
surely = seguramente
thoroughly = a fondo/minuciosamente
thus = así/por lo tanto
truly = verdaderamente/realmente
typically = típicamente/normalmente
ultimately = en última instancia/al final
undoubtedly = sin duda/indudablemente
utterly = completamente/totalmente
virtually = prácticamente/casi
whereas = mientras que
wherever = dondequiera/donde sea
whenever = cuando sea/siempre que
whatever = lo que sea/cualquier cosa
whoever = quienquiera/quien sea
however much = por mucho que
despite = a pesar de
in spite of = a pesar de/pese a
due to = debido a
owing to = debido a/a causa de
thanks to = gracias a
regarding = en cuanto a/respecto a
concerning = acerca de/sobre/en cuanto a
apart from = aparte de/además de
except = excepto/salvo/menos
including = incluso/incluido
beyond = más allá de
within = dentro de
throughout = a lo largo de/durante todo
underneath = debajo de
beside = al lado de/junto a
among = entre
along = a lo largo de
opposite = enfrente de/frente a
upon = sobre/al
provided that = siempre que/con tal de que
in order to = para/con el fin de
so as to = para/a fin de
as a result = como resultado/como consecuencia
in other words = en otras palabras/es decir
on the contrary = al contrario/por el contrario
in short = en resumen/en pocas palabras
to sum up = en resumen/para resumir
first of all = en primer lugar/primero
above all = sobre todo/ante todo
as well = también
as well as = así como/además de
no matter = no importa
no wonder = no es de extrañar/con razón
it depends = depende
what a pity = qué pena/qué lástima
never mind = no importa/da igual
it doesn't matter = no importa/da igual
I don't care = me da igual/no me importa
watch out = cuidado/ojo
go ahead = adelante
come on = vamos/venga/ándale
cheers = salud
bless you = salud/jesús
congratulations = felicidades/enhorabuena
good luck = buena suerte/suerte
take care = cuídate
have a good trip = buen viaje
enjoy your meal = buen provecho/que aproveche
welcome = bienvenido/bienvenida
`);
