addWords("B1", `
to achieve = lograr/conseguir/alcanzar
to reach = alcanzar/llegar
to add = añadir/agregar/sumar
to remove = quitar/eliminar
to include = incluir
to avoid = evitar
to suggest = sugerir/proponer
to propose = proponer
to recommend = recomendar
to advise = aconsejar
to warn = advertir/avisar
to inform = informar
to announce = anunciar
to report = informar/denunciar
to express = expresar
to mention = mencionar
to admit = admitir/reconocer
to deny = negar
to confirm = confirmar
to insist = insistir
to demand = exigir
to require = requerir/exigir
to request = solicitar/pedir
to obey = obedecer
to forbid = prohibir
to prohibit = prohibir
to punish = castigar
to forgive = perdonar
to blame = culpar/echar la culpa
to judge = juzgar
to trust = confiar
to deserve = merecer
to respect = respetar
to support = apoyar
to defend = defender
to attack = atacar
to win (a battle) = vencer
to defeat = derrotar/vencer
to surrender = rendirse
to compete = competir
to participate = participar
to join = unirse/juntar
to gather = reunir/juntar
to meet (a group) = reunirse
to separate = separar
to divide = dividir
to mix = mezclar
to combine = combinar
to increase = aumentar
to decrease = disminuir/reducir
to reduce = reducir
to grow (increase) = crecer/aumentar
to develop = desarrollar
to produce = producir
to create = crear
to invent = inventar
to discover = descubrir
to explore = explorar
to investigate = investigar
to analyze = analizar
to solve = resolver/solucionar
to prove = demostrar/probar
to test = probar
to calculate = calcular
to estimate = estimar/calcular
to predict = predecir
to expect = esperar
to suppose = suponer
to assume = suponer/asumir
to consider = considerar
to reflect = reflexionar/reflejar
to concentrate = concentrarse
to pay attention = prestar atención
to ignore = ignorar
to mind (care) = importar
to matter = importar
to interest = interesar
to bore = aburrir
to surprise = sorprender
to scare = asustar
to frighten = asustar/espantar
to calm down = calmarse/tranquilizarse
to relax = relajarse
to get angry = enfadarse/enojarse
to get upset = molestarse
to get nervous = ponerse nervioso
to get tired = cansarse
to get sick = enfermarse
to get better = mejorarse/mejorar
to recover = recuperarse/recuperar
to suffer = sufrir
to bleed = sangrar
to injure = herir/lastimar
to cure = curar
to heal = curar/sanar
to treat = tratar
to operate = operar
to vaccinate = vacunar
to exercise = hacer ejercicio
to train = entrenar
to stretch = estirar
to lose weight = adelgazar/bajar de peso
to gain weight = engordar
to diet = hacer dieta
to quit (stop doing) = dejar de
to try to = tratar de/intentar
to get used to = acostumbrarse
to be used to = estar acostumbrado/soler
to tend to = soler/tender
to manage to = lograr/conseguir
to dare = atreverse
to hesitate = dudar/vacilar
to regret = arrepentirse/lamentar
to miss (someone) = extrañar/echar de menos
to miss (a bus) = perder
to fall in love = enamorarse
to date (someone) = salir con
to break up = romper/separarse
to argue (fight) = pelearse/discutir
to get along = llevarse bien
to take advantage = aprovechar
to waste = desperdiciar/malgastar
to recycle = reciclar
to pollute = contaminar
to destroy = destruir
to burn = quemar
to freeze = congelar/helar
to melt = derretir
to flow = fluir/correr
to sink = hundirse
to float = flotar
to shake = sacudir/temblar
to tremble = temblar
to bend = doblar
to fold = doblar
to tie = atar/amarrar
to wrap = envolver
to hang = colgar
to lift = levantar
to drop = dejar caer/soltar
to let go = soltar
to grab = agarrar
to press = apretar/presionar
to squeeze = apretar/exprimir
to pour = verter/echar
to spread = extender/untar
to cover = cubrir/tapar
to uncover = descubrir/destapar
to fill in = completar/rellenar
to lock = cerrar con llave
to knock down = derribar/tirar
to dig = cavar/excavar
to plant = plantar/sembrar
to grow (cultivate) = cultivar
to harvest = cosechar
to feed = alimentar/dar de comer
to hunt = cazar
to fish = pescar
to sail = navegar
to land = aterrizar
to take off (plane) = despegar
to arrive late = llegar tarde
to delay = retrasar/demorar
to cancel = cancelar
to postpone = posponer/aplazar
to schedule = programar
to attend = asistir
to assist = ayudar/atender
to apply (for) = solicitar
to hire = contratar
to fire (dismiss) = despedir
to resign = renunciar/dimitir
to retire = jubilarse/retirarse
to earn a living = ganarse la vida
to invest = invertir
to owe = deber
should (ought to) = deber
to charge (money) = cobrar
to afford = permitirse
to manage (run) = dirigir/gestionar/administrar
to lead = dirigir/guiar/liderar
to guide = guiar
to direct = dirigir
to control = controlar
to govern = gobernar
to rule = gobernar/reinar
to vote = votar
to elect = elegir
to protest = protestar
to complain about = quejarse de
to fight for = luchar por
to sue = demandar
to arrest = arrestar/detener
to rob = robar/atracar
to murder = asesinar
to threaten = amenazar
to cheat = engañar/hacer trampa
to deceive = engañar
to betray = traicionar
to pretend = fingir/aparentar
to hide (conceal) = ocultar
to reveal = revelar
to publish = publicar
to broadcast = emitir/transmitir
to record = grabar
to film = filmar/rodar
to edit = editar
to design = diseñar
to decorate = decorar/adornar
to paint (a wall) = pintar
to repair = reparar/arreglar
to install = instalar
to replace = reemplazar/sustituir
to restore = restaurar
to maintain = mantener
to preserve = conservar/preservar
to store = almacenar/guardar
to collect = coleccionar/recoger
to pick up = recoger
to tidy up = ordenar/recoger
to iron = planchar
to sew = coser
to knit = tejer
to sweep = barrer
to mop = fregar/trapear
to wash the dishes = fregar los platos/lavar los platos
to make the bed = hacer la cama
to set the table = poner la mesa
to clear the table = recoger la mesa/quitar la mesa
to go shopping = ir de compras
to try on = probarse
to complain (formal) = reclamar
to bargain = regatear
to wrap up = envolver
to celebrate a birthday = cumplir años
to blow out = apagar/soplar
to toast = brindar
to raise = levantar/criar/subir
to raise (children) = criar
to educate = educar
to behave = comportarse/portarse
to obey rules = cumplir las reglas
to fulfill = cumplir
to keep (a promise) = cumplir
to belong to = pertenecer a
to own = poseer/tener
to lack = faltar/carecer
to be missing = faltar
to be left (remain) = quedar
to remain = permanecer/quedar
to last = durar
to take (time) = tardar
to be late = llegar tarde/retrasarse
to be on time = llegar a tiempo
to come back = volver/regresar
to go back = volver/regresar
to go away = irse/marcharse
to get lost = perderse
to look like = parecerse a/parecer
to resemble = parecerse
to fit in = encajar
to suit = quedar bien/sentar bien
to match = combinar/coincidir
to mean (intend) = querer decir
to point = señalar/apuntar
to sign up = inscribirse/apuntarse
to register = registrar/registrarse
to log in = iniciar sesión/entrar
to click = hacer clic/pulsar
to type = teclear/escribir
to save (a file) = guardar
to delete = borrar/eliminar
to share (online) = compartir
to follow (online) = seguir
to chat = chatear/charlar
to text = mandar un mensaje/escribir
to video call = hacer una videollamada
to update = actualizar
to browse = navegar
environment = medio ambiente/entorno
nature = naturaleza
climate = clima
climate change = cambio climático
pollution = contaminación
recycling = reciclaje
energy = energía
electricity = electricidad
gas = gas
fuel = combustible
petrol = gasolina
coal = carbón
air = aire
smoke = humo
dust = polvo
mud = barro/lodo
rock = roca
cave = cueva
volcano = volcán
earthquake = terremoto/sismo
flood = inundación
drought = sequía
hurricane = huracán
disaster = desastre
planet = planeta
universe = universo
space = espacio
continent = continente
ocean = océano
shore = orilla
bay = bahía
port = puerto
border = frontera
region = región
area = zona/área
province = provincia
state = estado
nation = nación
government = gobierno
president = presidente/presidenta
minister = ministro/ministra
king = rey
queen = reina
prince = príncipe
princess = princesa
politics = política
policy = política
party (political) = partido
election = elecciones/elección
vote = voto
democracy = democracia
law = ley
right (entitlement) = derecho
duty = deber
justice = justicia
court = tribunal/corte
judge = juez/jueza
trial = juicio
crime = crimen/delito
criminal = criminal/delincuente
thief = ladrón/ladrona
prison = cárcel/prisión
victim = víctima
witness = testigo
evidence = prueba/pruebas
fine (penalty) = multa
war = guerra
peace = paz
army = ejército
weapon = arma
gun = pistola/arma
bomb = bomba
enemy = enemigo/enemiga
battle = batalla
victory = victoria
defeat = derrota
freedom = libertad
power = poder
force = fuerza
strength = fuerza
society = sociedad
community = comunidad
population = población
citizen = ciudadano/ciudadana
immigrant = inmigrante
foreigner = extranjero/extranjera
foreign = extranjero
culture = cultura
custom = costumbre
tradition = tradición
religion = religión
God = Dios
soul = alma
spirit = espíritu
belief = creencia
faith = fe
history = historia
art = arte
science = ciencia
technology = tecnología
research = investigación
experiment = experimento
discovery = descubrimiento
invention = invento/invención
machine = máquina
tool = herramienta
device = dispositivo/aparato
engine = motor
wheel = rueda
factory = fábrica
industry = industria
company = empresa/compañía
business = negocio/empresa
economy = economía
market (economy) = mercado
product = producto
service = servicio
quality = calidad
quantity = cantidad
amount = cantidad
cost = costo/coste
profit = ganancia/beneficio
loss = pérdida
debt = deuda
loan = préstamo
tax = impuesto
salary = salario/sueldo
income = ingresos
budget = presupuesto
contract = contrato
interview = entrevista
career = carrera
experience = experiencia
skill = habilidad/destreza
ability = capacidad/habilidad
knowledge = conocimiento
training = formación/entrenamiento
course = curso
subject (school) = asignatura/materia
exam = examen
test = prueba/examen
grade (mark) = nota/calificación
degree (university) = título/licenciatura
homework = deberes/tarea
lesson = lección
mistake = error/equivocación
error = error
rule = regla/norma
meeting = reunión
conference = conferencia/congreso
project = proyecto
plan = plan
goal (objective) = objetivo/meta
purpose = propósito/fin
result = resultado
success = éxito
failure = fracaso
effort = esfuerzo
opportunity = oportunidad
chance (opportunity) = oportunidad
chance (luck) = suerte/casualidad
luck = suerte
risk = riesgo
advantage = ventaja
disadvantage = desventaja/inconveniente
benefit = beneficio
reason = razón/motivo
cause = causa
effect = efecto
consequence = consecuencia
solution = solución
choice = elección/opción
option = opción
decision = decisión
opinion = opinión
point of view = punto de vista
advice = consejo
suggestion = sugerencia
proposal = propuesta
agreement = acuerdo
argument (dispute) = discusión/pelea
discussion = discusión/debate
conversation = conversación
speech = discurso
fact = hecho
truth = verdad
lie (untruth) = mentira
secret = secreto
mystery = misterio
rumor = rumor
information = información
data = datos
detail = detalle
list = lista
form (document) = formulario
document = documento
report = informe/reporte
sign (notice) = señal/letrero/cartel
signal = señal
symbol = símbolo
meaning = significado
sense = sentido
feeling = sentimiento/sensación
emotion = emoción
mood = humor/estado de ánimo
happiness = felicidad
sadness = tristeza
joy = alegría
fear = miedo
anger = ira/enfado/enojo
hope = esperanza
pride = orgullo
shame = vergüenza
jealousy = celos/envidia
envy = envidia
stress = estrés
anxiety = ansiedad
pleasure = placer
fun (enjoyment) = diversión
surprise = sorpresa
memory = memoria/recuerdo
dream = sueño
nightmare = pesadilla
sleep = sueño
thought = pensamiento
mind = mente
attention = atención
patience = paciencia
character = carácter/personaje
personality = personalidad
behavior = comportamiento/conducta
habit = hábito/costumbre
relationship = relación
friendship = amistad
trust = confianza
respect = respeto
generation = generación
relative (family) = pariente/familiar
ancestor = antepasado
owner = dueño/propietario
member = miembro
leader = líder/jefe
partner = socio/pareja/compañero
enemy (rival) = rival
hero = héroe
character (story) = personaje
author = autor/autora
reader = lector/lectora
audience = público/audiencia
spectator = espectador
fan = aficionado/fan
crowd = multitud/muchedumbre
group = grupo
event = evento/acontecimiento
festival = festival
celebration = celebración
ceremony = ceremonia
exhibition = exposición/exhibición
show (performance) = espectáculo/función
stage = escenario
screen (cinema) = pantalla
scene = escena
chapter = capítulo
title = título
article = artículo
headline = titular
advertisement = anuncio
brand = marca
media = medios de comunicación/medios
press = prensa
social media = redes sociales
network = red
app = aplicación/app
account = cuenta
user = usuario/usuaria
link = enlace/vínculo
video = vídeo/video
image = imagen
text = texto
print (copy) = copia/impresión
health care = sanidad/atención médica
disease = enfermedad
illness = enfermedad
symptom = síntoma
injury = herida/lesión
wound = herida
treatment = tratamiento
surgery = cirugía/operación
patient = paciente
diet = dieta/alimentación
exercise = ejercicio
weight = peso
height = altura/estatura
size (dimension) = tamaño
shape = forma
length = longitud/largo
width = anchura/ancho
depth = profundidad
distance = distancia
speed = velocidad
level = nivel
step = paso
stage (phase) = etapa/fase
process = proceso
system = sistema
method = método
way (route) = camino/vía
path = sendero/camino
trip (outing) = excursión/salida
adventure = aventura
journey (route) = recorrido/trayecto
destination = destino
arrival = llegada
departure = salida/partida
delay = retraso/demora
customs = aduana
visa = visado/visa
accommodation = alojamiento
hostel = albergue/hostal
campsite = camping/campamento
tent = tienda de campaña/carpa
guidebook = guía
guide = guía
souvenir = recuerdo
view = vista
landscape = paisaje
sunset = atardecer/puesta de sol
sunrise = amanecer/salida del sol
shadow = sombra
shade = sombra
darkness = oscuridad
neighborhood (district) = barrio/distrito
suburb = afueras/suburbio
downtown = centro
farm = granja
crop = cultivo/cosecha
harvest = cosecha
wheat = trigo
rural = rural
urban = urbano
local = local
national = nacional
international = internacional
global = global/mundial
political = político
social = social
economic = económico
cultural = cultural
natural = natural
human = humano
personal = personal
professional = profesional
official = oficial
legal = legal
illegal = ilegal
current = actual
recent = reciente
previous = anterior
next = próximo/siguiente
following = siguiente
final = final
main = principal
basic = básico
simple = sencillo/simple
complex = complejo
complicated = complicado
clear = claro
obvious = obvio
sure = seguro
certain = cierto/seguro
likely = probable
unlikely = improbable/poco probable
probable = probable
real = real/verdadero
false = falso
fake = falso/falsificado
exact = exacto
general = general
specific = específico/concreto
special = especial
unique = único
rare = raro/poco común
common = común
frequent = frecuente
regular = regular
constant = constante
permanent = permanente
temporary = temporal/provisional
available = disponible
useful = útil
useless = inútil
valuable = valioso
expensive (costly) = costoso
worth = valer la pena
fair = justo
unfair = injusto
equal (same) = igual
free (liberated) = libre
independent = independiente
responsible = responsable
guilty = culpable
innocent = inocente
dangerous (risky) = arriesgado
healthy = sano/saludable
pregnant = embarazada
blind = ciego
deaf = sordo
pale = pálido
hurt (injured) = herido/lastimado
asleep = dormido
awake = despierto
drunk = borracho
excited = emocionado/ilusionado
disappointed = decepcionado/desilusionado
embarrassed = avergonzado/apenado
confused = confundido/confuso
lonely = solitario/solo
upset = disgustado/molesto
satisfied = satisfecho
grateful = agradecido
jealous = celoso/envidioso
generous = generoso
selfish = egoísta
patient (adjective) = paciente
curious = curioso
creative = creativo
clever = listo/inteligente
stupid = tonto/estúpido
silly = tonto/bobo
wise = sabio
mature = maduro
sensitive = sensible
sensible = sensato
reasonable = razonable
nice (pleasant) = agradable
pleasant = agradable
unpleasant = desagradable
comfortable = cómodo
uncomfortable = incómodo
quiet (silent) = silencioso
noisy = ruidoso
crowded = lleno de gente/abarrotado
lovely = encantador/precioso
wonderful = maravilloso
amazing = increíble/asombroso
incredible = increíble
terrible = terrible/horrible
horrible = horrible
awful = horrible/fatal
perfect = perfecto
excellent = excelente
fantastic = fantástico
great = genial/estupendo
huge = enorme
tiny = diminuto/pequeñito
enormous = enorme
little = pequeño/poco
slightly = ligeramente/un poco
quite = bastante
rather = bastante/más bien
completely = completamente/totalmente
totally = totalmente
absolutely = absolutamente
exactly = exactamente
nearly = casi
hardly = apenas
probably = probablemente
certainly = ciertamente/sin duda
definitely = definitivamente/sin duda
obviously = obviamente
clearly = claramente
suddenly = de repente/de pronto
finally = finalmente/por fin
at last = por fin
at least = al menos/por lo menos
at first = al principio
in the end = al final
immediately = inmediatamente/enseguida
right away = enseguida/ahora mismo
recently = recientemente/últimamente
lately = últimamente
nowadays = hoy en día/actualmente
currently = actualmente
meanwhile = mientras tanto
afterwards = después/luego
later = más tarde/luego
earlier = antes/más temprano
on time = a tiempo
in time = a tiempo
forever = para siempre
ever = alguna vez/jamás
anymore = ya no
even = incluso/hasta/aun
even though = aunque/aun cuando
unless = a menos que/a no ser que
in case = en caso de que/por si
so that = para que
as soon as = en cuanto/tan pronto como
as long as = mientras/siempre que
as if = como si
whether = si
otherwise = si no/de lo contrario
therefore = por lo tanto/por eso
besides = además
moreover = además
also (in addition) = además
in addition = además
on the other hand = por otro lado/por otra parte
for example = por ejemplo
that is = es decir/o sea
in fact = de hecho/en realidad
actually = en realidad/de hecho
indeed = efectivamente/en efecto
by the way = por cierto
by chance = por casualidad
on purpose = a propósito/adrede
on foot = a pie/andando
by heart = de memoria
out loud = en voz alta
in a hurry = deprisa/con prisa
little by little = poco a poco
from time to time = de vez en cuando
upside down = al revés/boca abajo
inside out = al revés
`);
