addWords("A1", `
the (masculine) = el
the (feminine) = la
a (masculine) = un
a (feminine) = una
and = y
or = o
but = pero
of = de
in = en
with = con
without = sin
for (purpose) = para
for (in exchange) = por
to = a
from = de/desde
that (conjunction) = que
what? = qué
who? = quién
where? = dónde
when? = cuándo
how? = cómo
why? = por qué
because = porque
how much? = cuánto
which? = cuál
yes = sí
no = no
not = no
I = yo
you (informal) = tú
you (formal) = usted
he = él
she = ella
we = nosotros/nosotras
they = ellos/ellas
you all = ustedes/vosotros/vosotras
my = mi
your (informal) = tu
his = su
our = nuestro/nuestra
me (object) = me
myself = me
with me = conmigo
with you (informal) = contigo
this (masculine) = este
this (feminine) = esta
that (masculine) = ese
that (feminine) = esa
this (neuter) = esto
that (neuter) = eso
here = aquí
there = allí/ahí/allá
very = muy
more = más
less = menos
a lot = mucho
a little = poco/un poco
too (also) = también
neither = tampoco
always = siempre
never = nunca/jamás
already = ya
still = todavía/aún
now = ahora
today = hoy
tomorrow = mañana
yesterday = ayer
then = entonces/luego
after = después
before = antes
soon = pronto
late = tarde
early = temprano
well = bien
badly = mal
so (thus) = así
also = también
only = solo/sólo/solamente
again = otra vez/de nuevo
everything = todo
nothing = nada
something = algo
someone = alguien
nobody = nadie
all = todos/todas
other = otro
each = cada
same = mismo
to be (permanent) = ser
to be (state, location) = estar
to have = tener
to have (auxiliary) = haber
there is = hay
to do = hacer
to make = hacer
to go = ir
to come = venir
to say = decir
to tell = decir/contar
to see = ver
to give = dar
to know (a fact) = saber
to know (a person) = conocer
to want = querer
to love = querer/amar
can (to be able) = poder
to put = poner
to think = pensar
to believe = creer
to speak = hablar
to talk = hablar
to eat = comer
to drink = beber/tomar
to live = vivir
to work = trabajar
to study = estudiar
to read = leer
to write = escribir
to learn = aprender
to understand = entender/comprender
to open = abrir
to close = cerrar
to buy = comprar
to sell = vender
to pay = pagar
to like = gustar
to need = necesitar
to look for = buscar
to find = encontrar
to leave = salir/dejar
to go out = salir
to enter = entrar
to arrive = llegar
to call = llamar
to wait = esperar
to hope = esperar
to take = tomar/llevar/coger
to carry = llevar
to bring = traer
to walk = caminar/andar
to run = correr
to sleep = dormir
to wake up = despertarse/despertar
to get up = levantarse
to sit down = sentarse
to play (a game) = jugar
to play (an instrument) = tocar
to sing = cantar
to dance = bailar
to cook = cocinar
to listen = escuchar
to hear = oír
to look at = mirar
to watch = mirar/ver
to ask (a question) = preguntar
to ask for = pedir
to answer = responder/contestar
to help = ayudar
to use = usar/utilizar
to begin = empezar/comenzar
to finish = terminar/acabar
to return = volver/regresar
to travel = viajar
to swim = nadar
to clean = limpiar
to wash = lavar
to change = cambiar
to feel = sentir/sentirse
to be called = llamarse
to understand (grasp) = comprender
to repeat = repetir
to wear = llevar/usar
to send = enviar/mandar
to visit = visitar
to rest = descansar
to remember = recordar/acordarse
to forget = olvidar
to try = intentar/probar
to have to = tener que
to be hungry = tener hambre
to be thirsty = tener sed
to be cold (person) = tener frío
to be hot (person) = tener calor
to be 20 years old = tener veinte años
hello = hola
goodbye = adiós
please = por favor
thank you = gracias
you're welcome = de nada
sorry = perdón/lo siento
excuse me = perdón/disculpe/perdone
good morning = buenos días
good afternoon = buenas tardes
good night = buenas noches
see you later = hasta luego
see you tomorrow = hasta mañana
nice to meet you = mucho gusto/encantado/encantada
how are you? = cómo estás/qué tal
okay = vale/de acuerdo/bueno
man = hombre
woman = mujer
boy = niño/chico
girl = niña/chica
child = niño/hijo
baby = bebé
person = persona
people = gente
friend (male) = amigo
friend (female) = amiga
family = familia
father = padre/papá
mother = madre/mamá
parents = padres
son = hijo
daughter = hija
brother = hermano
sister = hermana
grandfather = abuelo
grandmother = abuela
husband = esposo/marido
wife = esposa/mujer
boyfriend = novio
girlfriend = novia
uncle = tío
aunt = tía
cousin = primo/prima
name = nombre
surname = apellido
house = casa
home = casa/hogar
apartment = apartamento/piso
room = habitación/cuarto
bedroom = dormitorio/habitación
kitchen = cocina
bathroom = baño
living room = sala/salón
door = puerta
window = ventana
table = mesa
chair = silla
bed = cama
floor (ground) = suelo/piso
wall = pared
roof = techo
key = llave
garden = jardín
street = calle
city = ciudad
town = pueblo
country = país
world = mundo
school = escuela/colegio
university = universidad
class = clase
teacher = profesor/profesora/maestro/maestra
student = estudiante/alumno/alumna
book = libro
notebook = cuaderno
pen = bolígrafo/boli/pluma
pencil = lápiz
paper = papel
page = página
word = palabra
question = pregunta
answer = respuesta
language = idioma/lengua
Spanish (language) = español
English (language) = inglés
work (job) = trabajo
job = trabajo/empleo
office = oficina
money = dinero
shop = tienda
market = mercado
supermarket = supermercado
restaurant = restaurante
bar = bar
hotel = hotel
hospital = hospital
bank = banco
church = iglesia
park = parque
beach = playa
sea = mar
river = río
mountain = montaña
sun = sol
moon = luna
star = estrella
sky = cielo
rain = lluvia
snow = nieve
wind = viento
weather = tiempo/clima
water = agua
fire = fuego
tree = árbol
flower = flor
animal = animal
dog = perro
cat = gato
bird = pájaro/ave
fish (animal) = pez
horse = caballo
cow = vaca
food = comida
bread = pan
milk = leche
coffee = café
tea = té
juice = jugo/zumo
beer = cerveza
wine = vino
egg = huevo
meat = carne
chicken = pollo
fish (food) = pescado
rice = arroz
fruit = fruta
apple = manzana
orange (fruit) = naranja
banana = plátano/banana
potato = papa/patata
tomato = tomate
cheese = queso
salt = sal
sugar = azúcar
soup = sopa
salad = ensalada
breakfast = desayuno
lunch = almuerzo/comida
dinner = cena
to have breakfast = desayunar
to have dinner = cenar
to have lunch = almorzar/comer
glass (for drinking) = vaso
cup = taza
plate = plato
fork = tenedor
knife = cuchillo
spoon = cuchara
bottle = botella
car = coche/carro/auto
bus = autobús/bus
train = tren
plane = avión
bicycle = bicicleta/bici
boat = barco
ticket = billete/boleto/entrada
station = estación
airport = aeropuerto
road = camino/carretera
time = tiempo
time (occurrence) = vez
hour = hora
minute = minuto
second (time) = segundo
day = día
week = semana
month = mes
year = año
morning = mañana
afternoon = tarde
evening = tarde/noche
night = noche
weekend = fin de semana
Monday = lunes
Tuesday = martes
Wednesday = miércoles
Thursday = jueves
Friday = viernes
Saturday = sábado
Sunday = domingo
January = enero
February = febrero
March = marzo
April = abril
May = mayo
June = junio
July = julio
August = agosto
September = septiembre/setiembre
October = octubre
November = noviembre
December = diciembre
spring = primavera
summer = verano
autumn = otoño
winter = invierno
one = uno
two = dos
three = tres
four = cuatro
five = cinco
six = seis
seven = siete
eight = ocho
nine = nueve
ten = diez
eleven = once
twelve = doce
thirteen = trece
fourteen = catorce
fifteen = quince
sixteen = dieciséis
seventeen = diecisiete
eighteen = dieciocho
nineteen = diecinueve
twenty = veinte
thirty = treinta
forty = cuarenta
fifty = cincuenta
sixty = sesenta
seventy = setenta
eighty = ochenta
ninety = noventa
hundred = cien/ciento
thousand = mil
million = millón
first = primero/primera
second (ordinal) = segundo
third = tercero/tercera
last = último/última
half = mitad/medio
red = rojo
blue = azul
green = verde
yellow = amarillo
black = negro
white = blanco
gray = gris
brown = marrón/café
pink = rosa/rosado
orange (color) = naranja/anaranjado
color = color
big = grande
small = pequeño/chico
good = bueno
bad = malo
new = nuevo
old (thing) = viejo
old (person) = viejo/mayor/anciano
young = joven
long = largo
short (length) = corto
short (height) = bajo
tall = alto
high = alto
low = bajo
hot = caliente/caluroso
cold = frío
pretty = bonito/lindo
beautiful = hermoso/bello/precioso
ugly = feo
happy = feliz/contento
sad = triste
tired = cansado
sick = enfermo
hungry = hambriento
easy = fácil
difficult = difícil
fast = rápido
slow = lento
cheap = barato
expensive = caro
open = abierto
closed = cerrado
full = lleno
empty = vacío
clean = limpio
dirty = sucio
rich = rico
poor = pobre
true = verdadero/cierto
important = importante
interesting = interesante
boring = aburrido
nice (kind) = simpático/amable
friendly = amable/simpático
intelligent = inteligente/listo
ready = listo/preparado
busy = ocupado
free (no cost) = gratis/gratuito
free (liberty) = libre
better = mejor
worse = peor
best = mejor/el mejor
first name = nombre
body = cuerpo
head = cabeza
face = cara
eye = ojo
ear = oreja/oído
nose = nariz
mouth = boca
tooth = diente
hair = pelo/cabello
hand = mano
arm = brazo
leg = pierna
foot = pie
heart = corazón
back (body) = espalda
clothes = ropa
shirt = camisa
T-shirt = camiseta/playera
pants = pantalones/pantalón
dress = vestido
skirt = falda
shoe = zapato
hat = sombrero
coat = abrigo
bag = bolsa/bolso
phone = teléfono
mobile phone = móvil/celular
computer = ordenador/computadora
television = televisión/tele
music = música
song = canción
movie = película
game = juego
sport = deporte
soccer = fútbol
ball = pelota/balón
party = fiesta
birthday = cumpleaños
gift = regalo
letter (mail) = carta
letter (alphabet) = letra
number = número
thing = cosa
place = lugar/sitio
part = parte
way (manner) = manera/forma/modo
problem = problema
idea = idea
example = ejemplo
moment = momento
life = vida
love = amor
health = salud
doctor = médico/doctor/doctora
left = izquierda
right (direction) = derecha
straight ahead = todo recto/derecho
near = cerca
far = lejos
in front of = delante de/enfrente de
behind = detrás de
on (on top of) = sobre/encima de
under = debajo de/bajo
between = entre
next to = al lado de
inside = dentro
outside = fuera/afuera
up = arriba
down = abajo
until = hasta
during = durante
about (topic) = sobre/de/acerca de
if = si
when (conjunction) = cuando
where (relative) = donde
like (as) = como
`);
